export const postsData = [
  {
    id: "1",
    title: "Course 1",
    speaker: "Metabillionaire",
    type: "mp4",
    size: "24.56 MB",
    duration: 54,
    video: "",
    publishedDate: "31st December",
    banner: "/banner.jpeg",
  },
  {
    id: "2",
    title: "Course 2",
    speaker: "Metabillionaire",
    type: "mp4",
    size: "24.56 MB",
    duration: 54,
    video: "",
    publishedDate: "31st December",
    banner: "/banner.jpeg",
  },
  {
    id: "3",
    title: "PDF 3",
    speaker: "Metabillionaire",
    type: "pdf",
    size: "24.56 MB",
    duration: 54,
    video: "",
    publishedDate: "31st December",
    banner: "/banner.jpeg",
  },
  {
    id: "4",
    title: "Course 4",
    speaker: "Metabillionaire",
    type: "mp4",
    size: "24.56 MB",
    duration: 54,
    video: "",
    publishedDate: "31st December",
    banner: "/banner.jpeg",
  },
  {
    id: "5",
    title: "Course 5",
    speaker: "Metabillionaire",
    type: "mp4",
    size: "24.56 MB",
    duration: 54,
    video: "",
    publishedDate: "31st December",
    banner: "/banner.jpeg",
  },
];
