export default skills;
const skills = [
  { value: "Graphics & Design", label: "Graphics & Design" },
  { value: "Logo Design", label: "Logo Design" },
  { value: "Brand Style Guides", label: "Brand Style Guides" },
  { value: "Game Art", label: "Game Art" },
  { value: "Character Design", label: "Character Design" },
  { value: "Props & Objects", label: "Props & Objects" },
  { value: "Backgrounds & Environments", label: "Backgrounds & Environments" },
  { value: "UI & UX", label: "UI & UX" },
  { value: "Graphics for Streamers", label: "Graphics for Streamers" },
  {
    value: "Business Cards & Stationery",
    label: "Business Cards & Stationery",
  },
  { value: "Website Design", label: "Website Design" },
  { value: "App Design", label: "App Design" },
  { value: "UX Design", label: "UX Design" },
  { value: "Landing Page Design", label: "Landing Page Design" },
  { value: "Resume Design", label: "Resume Design" },
  { value: "Illustration", label: "Illustration" },
  { value: "NFT Art", label: "NFT Art" },
  { value: "Pattern Design", label: "Pattern Design" },
  { value: "Fonts & Typography", label: "Fonts & Typography" },
  { value: "Font Design", label: "Font Design" },
  { value: "Typography", label: "Typography" },
  { value: "Hand Lettering", label: "Hand Lettering" },
  { value: "Calligraphy", label: "Calligraphy" },
  { value: "Brochure Design", label: "Brochure Design" },
  { value: "Poster Design", label: "Poster Design" },
  { value: "Flyer Design", label: "Flyer Design" },
  { value: "Book Design", label: "Book Design" },
  {
    value: "Book Layout Design & Typesetting",
    label: "Book Layout Design & Typesetting",
  },
  { value: "Book Cover Design", label: "Book Cover Design" },
  { value: "Album Cover Design", label: "Album Cover Design" },
  { value: "Podcast Cover Art", label: "Podcast Cover Art" },
  { value: "Packaging & Label Design", label: "Packaging & Label Design" },
  { value: "Packaging Design", label: "Packaging Design" },
  { value: "Label Design", label: "Label Design" },
  { value: "Dieline Design", label: "Dieline Design" },
  { value: "Storyboards", label: "Storyboards" },
  { value: "Social Media Design", label: "Social Media Design" },
  { value: "Headers & Covers", label: "Headers & Covers" },
  { value: "Social Posts & Banners", label: "Social Posts & Banners" },
  { value: "Thumbnails Design", label: "Thumbnails Design" },
  { value: "AR Filters & Lenses", label: "AR Filters & Lenses" },
  { value: "Catalog Design", label: "Catalog Design" },
  { value: "Menu Design", label: "Menu Design" },
  { value: "Invitation Design", label: "Invitation Design" },
  { value: "Portraits & Caricatures", label: "Portraits & Caricatures" },
  { value: "Cartoons & Comics", label: "Cartoons & Comics" },
  { value: "Tattoo Design", label: "Tattoo Design" },
  { value: "Signage Design", label: "Signage Design" },
  { value: "Web Banners", label: "Web Banners" },
  { value: "Image Editing", label: "Image Editing" },
  { value: "Product Image Editing", label: "Product Image Editing" },
  { value: "Photo Manipulation", label: "Photo Manipulation" },
  { value: "Portraits Retouching", label: "Portraits Retouching" },
  { value: "Photo Restoration", label: "Photo Restoration" },
  { value: "Mockups", label: "Mockups" },
  {
    value: "Architecture & Interior Design",
    label: "Architecture & Interior Design",
  },
  { value: "Diagrams & Mapping", label: "Diagrams & Mapping" },
  { value: "Virtual Staging", label: "Virtual Staging" },
  { value: "Planning & Design", label: "Planning & Design" },
  { value: "3D Modeling & Rendering", label: "3D Modeling & Rendering" },
  { value: "2D Drawings & Floor Plans", label: "2D Drawings & Floor Plans" },
  { value: "Landscape Design", label: "Landscape Design" },
  { value: "Planning & Design", label: "Planning & Design" },
  { value: "3D Modeling & Rendering", label: "3D Modeling & Rendering" },
  { value: "2D Drawings & Site Plans", label: "2D Drawings & Site Plans" },
  { value: "Building Engineering", label: "Building Engineering" },
  { value: "HVAC", label: "HVAC" },
  { value: "Electrical Engineering", label: "Electrical Engineering" },
  { value: "Plumbing & Drainage", label: "Plumbing & Drainage" },
  { value: "Civil & Structural", label: "Civil & Structural" },
  {
    value: "Building Information Modeling",
    label: "Building Information Modeling",
  },
  {
    value: "BIM 4D Construction Simulation",
    label: "BIM 4D Construction Simulation",
  },
  {
    value: "BIM Online Training & Implementation",
    label: "BIM Online Training & Implementation",
  },
  { value: "BIM Family Creation", label: "BIM Family Creation" },
  {
    value: "BIM Coordination & Clash Detection",
    label: "BIM Coordination & Clash Detection",
  },
  { value: "BIM 3D Modeling", label: "BIM 3D Modeling" },
  { value: "Character Modeling", label: "Character Modeling" },
  {
    value: "Industrial & Product Design",
    label: "Industrial & Product Design",
  },
  { value: "Concept Development", label: "Concept Development" },
  { value: "3D Modeling & Rendering", label: "3D Modeling & Rendering" },
  { value: "Prototyping & 3D Printing", label: "Prototyping & 3D Printing" },
  { value: "Product Manufacturing", label: "Product Manufacturing" },
  { value: "2D Drawing", label: "2D Drawing" },
  { value: "Trade Booth Design", label: "Trade Booth Design" },
  { value: "T-Shirts & Merchandise", label: "T-Shirts & Merchandise" },
  { value: "Fashion Design", label: "Fashion Design" },
  {
    value: "Technical Drawing & Tech Pack",
    label: "Technical Drawing & Tech Pack",
  },
  { value: "Pattern Making", label: "Pattern Making" },
  { value: "Fashion Illustration", label: "Fashion Illustration" },
  { value: "3D Garment Design", label: "3D Garment Design" },
  { value: "Full Design Process", label: "Full Design Process" },
  { value: "Jewelry Design", label: "Jewelry Design" },
  { value: "3D Modeling & Rendering", label: "3D Modeling & Rendering" },
  { value: "Concept Design & Sketching", label: "Concept Design & Sketching" },
  { value: "Presentation Design", label: "Presentation Design" },
  { value: "Email Design", label: "Email Design" },
  { value: "Icon Design", label: "Icon Design" },
  { value: "Infographic Design", label: "Infographic Design" },
  { value: "Car Wraps", label: "Car Wraps" },
  { value: "Vector Tracing", label: "Vector Tracing" },
  { value: "Other", label: "Other" },
  { value: "Design Advice", label: "Design Advice" },
  {
    value: "Design Review & Consultation",
    label: "Design Review & Consultation",
  },
  { value: "Design Mentorship", label: "Design Mentorship" },
  { value: "Design Lessons", label: "Design Lessons" },
  { value: "Writing & Translation", label: "Writing & Translation" },
  { value: "Articles & Blog Posts", label: "Articles & Blog Posts" },
  { value: "Proofreading & Editing", label: "Proofreading & Editing" },
  { value: "Proofreading", label: "Proofreading" },
  { value: "Copy Editing", label: "Copy Editing" },
  { value: "Translation", label: "Translation" },
  { value: "Website Content", label: "Website Content" },
  { value: "Product Descriptions", label: "Product Descriptions" },
  { value: "Book & eBook Writing", label: "Book & eBook Writing" },
  { value: "Kindle Niche Research", label: "Kindle Niche Research" },
  { value: "Short Stories", label: "Short Stories" },
  { value: "Book Proposals", label: "Book Proposals" },
  { value: "Book Blurbs", label: "Book Blurbs" },
  { value: "Ghostwriting", label: "Ghostwriting" },
  { value: "Book Editing", label: "Book Editing" },
  { value: "Resume Writing", label: "Resume Writing" },
  { value: "Brand Voice & Tone", label: "Brand Voice & Tone" },
  { value: "UX Writing", label: "UX Writing" },
  { value: "Email Copy", label: "Email Copy" },
  { value: "Technical Writing", label: "Technical Writing" },
  { value: "White Papers", label: "White Papers" },
  { value: "Sales Copy", label: "Sales Copy" },
  { value: "Social Media Copy", label: "Social Media Copy" },
  { value: "Podcast Writing", label: "Podcast Writing" },
  { value: "Podcast Content", label: "Podcast Content" },
  { value: "Podcast Show Notes", label: "Podcast Show Notes" },
  { value: "Ad Copy", label: "Ad Copy" },
  { value: "Cover Letters", label: "Cover Letters" },
  { value: "Press Releases", label: "Press Releases" },
  { value: "Case Studies", label: "Case Studies" },
  { value: "LinkedIn Profiles", label: "LinkedIn Profiles" },
  { value: "Job Descriptions", label: "Job Descriptions" },
  { value: "Creative Writing", label: "Creative Writing" },
  { value: "Game Writing", label: "Game Writing" },
  { value: "Poetry", label: "Poetry" },
  { value: "Song Lyrics", label: "Song Lyrics" },
  { value: "Letters", label: "Letters" },
  { value: "Beta Reading", label: "Beta Reading" },
  { value: "Scriptwriting", label: "Scriptwriting" },
  { value: "Other Scriptwriting", label: "Other Scriptwriting" },
  { value: "Consultation", label: "Consultation" },
  { value: "Webinars", label: "Webinars" },
  { value: "Cold Calls", label: "Cold Calls" },
  { value: "Meditation Scripts", label: "Meditation Scripts" },
  { value: "Audio Ads", label: "Audio Ads" },
  { value: "Script Coverage", label: "Script Coverage" },
  { value: "Film & TV Screenplays", label: "Film & TV Screenplays" },
  { value: "Video Scripts", label: "Video Scripts" },
  { value: "Business Names & Slogans", label: "Business Names & Slogans" },
  {
    value: "eLearning Content Development",
    label: "eLearning Content Development",
  },
  { value: "Speechwriting", label: "Speechwriting" },
  { value: "Grant Writing", label: "Grant Writing" },
  { value: "Grant Research", label: "Grant Research" },
  { value: "Grant Proposals", label: "Grant Proposals" },
  { value: "Transcription", label: "Transcription" },
  { value: "Research & Summaries", label: "Research & Summaries" },
  { value: "Other", label: "Other" },
  { value: "Writing Advice", label: "Writing Advice" },
  { value: "Writing Mentorship", label: "Writing Mentorship" },
  { value: "Writing Lessons", label: "Writing Lessons" },
  { value: "Video & Animation", label: "Video & Animation" },
  {
    value: "Whiteboard & Animated Explainers",
    label: "Whiteboard & Animated Explainers",
  },
  { value: "2D Animated Explainers", label: "2D Animated Explainers" },
  { value: "3D Animated Explainers", label: "3D Animated Explainers" },
  { value: "Isometric Explainers", label: "Isometric Explainers" },
  { value: "Whiteboard Explainers", label: "Whiteboard Explainers" },
  { value: "Video Editing", label: "Video Editing" },
  { value: "Video Ads & Commercials", label: "Video Ads & Commercials" },
  { value: "Animated GIFs", label: "Animated GIFs" },
  { value: "Logo Animation", label: "Logo Animation" },
  { value: "Intro & Outro Videos", label: "Intro & Outro Videos" },
  { value: "Character Animation", label: "Character Animation" },
  { value: "3D Product Animation", label: "3D Product Animation" },
  { value: "Social Media Videos", label: "Social Media Videos" },
  { value: "Music Videos", label: "Music Videos" },
  { value: "Lyric Videos", label: "Lyric Videos" },
  { value: "Music Visualization", label: "Music Visualization" },
  { value: "Dance Videos", label: "Dance Videos" },
  { value: "Narrative-Based Videos", label: "Narrative-Based Videos" },
  { value: "Performance Videos", label: "Performance Videos" },
  { value: "Conceptual Videos", label: "Conceptual Videos" },
  { value: "Anime Music Videos", label: "Anime Music Videos" },
  { value: "Spotify Canvas", label: "Spotify Canvas" },
  { value: "NFT Animation", label: "NFT Animation" },
  { value: "Animation for Kids", label: "Animation for Kids" },
  { value: "Animation for Streamers", label: "Animation for Streamers" },
  { value: "Live Action Explainers", label: "Live Action Explainers" },
  { value: "Filmed Video Production", label: "Filmed Video Production" },
  { value: "Videographers", label: "Videographers" },
  { value: "E-Commerce Product Videos", label: "E-Commerce Product Videos" },
  { value: "Spokespersons Videos", label: "Spokespersons Videos" },
  { value: "Subtitles & Captions", label: "Subtitles & Captions" },
  { value: "Visual Effects", label: "Visual Effects" },
  {
    value: "Rotoscoping & Chroma Keying",
    label: "Rotoscoping & Chroma Keying",
  },
  { value: "Color Grading", label: "Color Grading" },
  { value: "Match Moving", label: "Match Moving" },
  { value: "Compositing", label: "Compositing" },
  { value: "Cleanups", label: "Cleanups" },
  { value: "Beauty Retouching", label: "Beauty Retouching" },
  { value: "Lottie & Web Animation", label: "Lottie & Web Animation" },
  { value: "eLearning Video Production", label: "eLearning Video Production" },
  { value: "Article to Video", label: "Article to Video" },
  { value: "Unboxing Videos", label: "Unboxing Videos" },
  { value: "Screencasting Videos", label: "Screencasting Videos" },
  { value: "Corporate Videos", label: "Corporate Videos" },
  { value: "Crowdfunding Videos", label: "Crowdfunding Videos" },
  { value: "Slideshow Videos", label: "Slideshow Videos" },
  { value: "Video Templates Editing", label: "Video Templates Editing" },
  { value: "App & Website Previews", label: "App & Website Previews" },
  { value: "Book Trailers", label: "Book Trailers" },
  { value: "Meditation Videos", label: "Meditation Videos" },
  { value: "Real Estate Promos", label: "Real Estate Promos" },
  { value: "Game Trailers", label: "Game Trailers" },
  { value: "Video Advice", label: "Video Advice" },
  {
    value: "Video Review & Consultation",
    label: "Video Review & Consultation",
  },
  { value: "Video Mentorship", label: "Video Mentorship" },
  { value: "Video Lessons", label: "Video Lessons" },
  { value: "Other", label: "Other" },
  { value: "Music & Audio", label: "Music & Audio" },
  { value: "Voice Over", label: "Voice Over" },
  { value: "Mixing & Mastering", label: "Mixing & Mastering" },
  { value: "Producers & Composers", label: "Producers & Composers" },
  { value: "Composing & Soundtracks", label: "Composing & Soundtracks" },
  { value: "Ghost Production", label: "Ghost Production" },
  { value: "Backing Tracks", label: "Backing Tracks" },
  { value: "Singers & Vocalists", label: "Singers & Vocalists" },
  { value: "Male Singers", label: "Male Singers" },
  { value: "Female Singers", label: "Female Singers" },
  { value: "Gender Neutral Singers", label: "Gender Neutral Singers" },
  { value: "Session Musicians", label: "Session Musicians" },
  { value: "Songwriters", label: "Songwriters" },
  { value: "Beat Making", label: "Beat Making" },
  { value: "Beats", label: "Beats" },
  { value: "Loops & Kits", label: "Loops & Kits" },
  { value: "Online Music Lessons", label: "Online Music Lessons" },
  { value: "Instruments", label: "Instruments" },
  { value: "Production", label: "Production" },
  { value: "Vocals", label: "Vocals" },
  { value: "Theory", label: "Theory" },
  { value: "Podcast Production", label: "Podcast Production" },
  { value: "Audiobook Production", label: "Audiobook Production" },
  { value: "Audio Ads Production", label: "Audio Ads Production" },
  { value: "Sound Design", label: "Sound Design" },
  { value: "Sound Effects", label: "Sound Effects" },
  { value: "Foley", label: "Foley" },
  { value: "Audio Editing", label: "Audio Editing" },
  { value: "Music Transcription", label: "Music Transcription" },
  { value: "Vocal Tuning", label: "Vocal Tuning" },
  { value: "DJ Drops & Tags", label: "DJ Drops & Tags" },
  { value: "DJ Drops", label: "DJ Drops" },
  { value: "Producer Tags", label: "Producer Tags" },
  { value: "DJ Mixing", label: "DJ Mixing" },
  { value: "Remixing & Mashups", label: "Remixing & Mashups" },
  { value: "Remixing", label: "Remixing" },
  { value: "Mashups", label: "Mashups" },
  { value: "Synth Presets", label: "Synth Presets" },
  { value: "Meditation Music", label: "Meditation Music" },
  { value: "Jingles & Intros", label: "Jingles & Intros" },
  { value: "Jingles", label: "Jingles" },
  { value: "Intros & Outros", label: "Intros & Outros" },
  {
    value: "Audio Logo & Sonic Branding",
    label: "Audio Logo & Sonic Branding",
  },
  { value: "Music & Audio Advice", label: "Music & Audio Advice" },
  { value: "Music & Audio Mentorship", label: "Music & Audio Mentorship" },
  { value: "Music Review & Feedback", label: "Music Review & Feedback" },
  { value: "Other", label: "Other" },
  { value: "Business", label: "Business" },
  { value: "ERP Management", label: "ERP Management" },
  { value: "CRM Management", label: "CRM Management" },
  { value: "Sales", label: "Sales" },
  { value: "Strategy & Planning", label: "Strategy & Planning" },
  { value: "Lead Generation", label: "Lead Generation" },
  { value: "Lead Qualification", label: "Lead Qualification" },
  { value: "Deal Development", label: "Deal Development" },
  { value: "Virtual Assistant", label: "Virtual Assistant" },
  { value: "Call Center & Calling", label: "Call Center & Calling" },
  { value: "Skip Tracing", label: "Skip Tracing" },
  { value: "File Conversion", label: "File Conversion" },
  { value: "Administration", label: "Administration" },
  { value: "Market Research", label: "Market Research" },
  { value: "Full Package Qual & Quant", label: "Full Package Qual & Quant" },
  { value: "Interviews & Focus Groups", label: "Interviews & Focus Groups" },
  { value: "Domain Name Research", label: "Domain Name Research" },
  { value: "General Online Research", label: "General Online Research" },
  { value: "Consultation", label: "Consultation" },
  { value: "Surveys", label: "Surveys" },
  { value: "Business Plans", label: "Business Plans" },
  {
    value: "Business Plans for Startups",
    label: "Business Plans for Startups",
  },
  {
    value: "Business Plans for Loan Approval",
    label: "Business Plans for Loan Approval",
  },
  {
    value: "Business Plans for Non-Profits",
    label: "Business Plans for Non-Profits",
  },
  {
    value: "Business Plans for Immigration",
    label: "Business Plans for Immigration",
  },
  {
    value: "Business Plans for Partnerships",
    label: "Business Plans for Partnerships",
  },
  { value: "Customer Care", label: "Customer Care" },
  { value: "Customer Support", label: "Customer Support" },
  { value: "Planning & Setup", label: "Planning & Setup" },
  { value: "Consulting", label: "Consulting" },
  { value: "Customer Success", label: "Customer Success" },
  { value: "Project Management", label: "Project Management" },
  { value: "Graphics & Design Projects", label: "Graphics & Design Projects" },
  { value: "Digital Marketing Projects", label: "Digital Marketing Projects" },
  {
    value: "Writing & Translation Projects",
    label: "Writing & Translation Projects",
  },
  { value: "Video & Animation Projects", label: "Video & Animation Projects" },
  { value: "Music & Audio Projects", label: "Music & Audio Projects" },
  {
    value: "Programming & Tech Projects",
    label: "Programming & Tech Projects",
  },
  { value: "General Project Services", label: "General Project Services" },
  { value: "HR Consulting", label: "HR Consulting" },
  { value: "Organizational Development", label: "Organizational Development" },
  {
    value: "Talent Acquisition & Recruitment",
    label: "Talent Acquisition & Recruitment",
  },
  { value: "Performance Management", label: "Performance Management" },
  {
    value: "Employee Learning & Development",
    label: "Employee Learning & Development",
  },
  { value: "Compensation & Benefits", label: "Compensation & Benefits" },
  { value: "HR Information Systems", label: "HR Information Systems" },
  { value: "E-Commerce Management", label: "E-Commerce Management" },
  { value: "Consultation", label: "Consultation" },
  { value: "Product Upload", label: "Product Upload" },
  { value: "Store Management", label: "Store Management" },
  { value: "Product Research", label: "Product Research" },
  { value: "Event Management", label: "Event Management" },
  { value: "Legal Consulting", label: "Legal Consulting" },
  { value: "Legal Research", label: "Legal Research" },
  {
    value: "Legal Documents & Contracts",
    label: "Legal Documents & Contracts",
  },
  { value: "General Legal Advice", label: "General Legal Advice" },
  { value: "Arbitration & Mediation", label: "Arbitration & Mediation" },
  {
    value: "Applications & Registrations",
    label: "Applications & Registrations",
  },
  { value: "Legal Disputes", label: "Legal Disputes" },
  { value: "Financial Consulting", label: "Financial Consulting" },
  {
    value: "Analysis, Valuation & Optimization",
    label: "Analysis, Valuation & Optimization",
  },
  { value: "Accounting & Bookkeeping", label: "Accounting & Bookkeeping" },
  { value: "Tax Consulting", label: "Tax Consulting" },
  {
    value: "Personal Finance & Wealth Management",
    label: "Personal Finance & Wealth Management",
  },
  {
    value: "Financial Forecasting & Modeling",
    label: "Financial Forecasting & Modeling",
  },
  { value: "Online Trading Lessons", label: "Online Trading Lessons" },
  { value: "Business Consulting", label: "Business Consulting" },
  { value: "Supply Chain Management", label: "Supply Chain Management" },
  { value: "Logistics", label: "Logistics" },
  {
    value: "Procurement & Vendor Management",
    label: "Procurement & Vendor Management",
  },
  { value: "Presentations", label: "Presentations" },
  { value: "Career Counseling", label: "Career Counseling" },
  { value: "Interview Prep", label: "Interview Prep" },
  { value: "Search & Apply", label: "Search & Apply" },
  { value: "Game Concept Design", label: "Game Concept Design" },
  { value: "Other", label: "Other" },
  { value: "Lifestyle", label: "Lifestyle" },
  { value: "Gaming", label: "Gaming" },
  { value: "Game Coaching", label: "Game Coaching" },
  { value: "Online Tutoring", label: "Online Tutoring" },
  { value: "Language Tutoring", label: "Language Tutoring" },
  { value: "Math Tutoring", label: "Math Tutoring" },
  { value: "Science Tutoring", label: "Science Tutoring" },
  { value: "Social Sciences Tutoring", label: "Social Sciences Tutoring" },
  { value: "Business Tutoring", label: "Business Tutoring" },
  { value: "Engineering Tutoring", label: "Engineering Tutoring" },
  { value: "Other Subjects", label: "Other Subjects" },
  { value: "Life Coaching", label: "Life Coaching" },
  { value: "Astrology & Psychics", label: "Astrology & Psychics" },
  { value: "Readings", label: "Readings" },
  { value: "Love & Relationships", label: "Love & Relationships" },
  { value: "Dream Analysis", label: "Dream Analysis" },
  { value: "Reiki", label: "Reiki" },
  { value: "Spell Casting", label: "Spell Casting" },
  { value: "Feng shui", label: "Feng shui" },
  { value: "Modeling & Acting", label: "Modeling & Acting" },
  { value: "Fitness Lessons", label: "Fitness Lessons" },
  { value: "Dance Lessons", label: "Dance Lessons" },
  { value: "Personal Stylists", label: "Personal Stylists" },
  { value: "Cooking Lessons", label: "Cooking Lessons" },
  { value: "Arts & Crafts", label: "Arts & Crafts" },
  { value: "Wellness", label: "Wellness" },
  { value: "Meal Plans", label: "Meal Plans" },
  { value: "Workout Plans", label: "Workout Plans" },
  { value: "Family & Genealogy", label: "Family & Genealogy" },
  { value: "Greeting Cards & Videos", label: "Greeting Cards & Videos" },
  { value: "Puzzle & Game Creation", label: "Puzzle & Game Creation" },
  { value: "Collectibles", label: "Collectibles" },
  { value: "Traveling", label: "Traveling" },
  { value: "Local Advisors", label: "Local Advisors" },
  { value: "Shipping Services", label: "Shipping Services" },
  { value: "Trip Plans", label: "Trip Plans" },
  { value: "Other", label: "Other" },
  { value: "Programming & Tech", label: "Programming & Tech" },
  { value: "Website Development", label: "Website Development" },
  { value: "WordPress", label: "WordPress" },
  { value: "Shopify", label: "Shopify" },
  { value: "Wix", label: "Wix" },
  { value: "Squarespace", label: "Squarespace" },
  { value: "Webflow", label: "Webflow" },
  { value: "GoDaddy", label: "GoDaddy" },
  { value: "WooCommerce", label: "WooCommerce" },
  { value: "ClickFunnels", label: "ClickFunnels" },
  { value: "Custom Websites", label: "Custom Websites" },
  { value: "Magento", label: "Magento" },
  { value: "SiteBuilder", label: "SiteBuilder" },
  { value: "Thinkific", label: "Thinkific" },
  { value: "Drupal", label: "Drupal" },
  { value: "Joomla", label: "Joomla" },
  { value: "Blogger", label: "Blogger" },
  { value: "Website Maintenance", label: "Website Maintenance" },
  { value: "Customization", label: "Customization" },
  { value: "Bug Fixes", label: "Bug Fixes" },
  { value: "Backup & Migration", label: "Backup & Migration" },
  { value: "Hosting", label: "Hosting" },
  {
    value: "Themes/Plugins Installation",
    label: "Themes/Plugins Installation",
  },
  { value: "Help/Consultation", label: "Help/Consultation" },
  { value: "Installation", label: "Installation" },
  { value: "Speed Optimization", label: "Speed Optimization" },
  { value: "Security", label: "Security" },
  { value: "Analytics", label: "Analytics" },
  { value: "Game Development", label: "Game Development" },
  { value: "Consultation", label: "Consultation" },
  { value: "Backup & Migration", label: "Backup & Migration" },
  { value: "Customization", label: "Customization" },
  { value: "Prototyping", label: "Prototyping" },
  { value: "Full Game Creation", label: "Full Game Creation" },
  { value: "Bug Fixes", label: "Bug Fixes" },
  { value: "Development for Streamers", label: "Development for Streamers" },
  { value: "Addons & Customization", label: "Addons & Customization" },
  { value: "Setup & Installation", label: "Setup & Installation" },
  { value: "Web Programming", label: "Web Programming" },
  { value: "Web Application", label: "Web Application" },
  { value: "Bug Fixes", label: "Bug Fixes" },
  { value: "Browser Extensions", label: "Browser Extensions" },
  { value: "Email Template", label: "Email Template" },
  { value: "Convert PSD", label: "Convert PSD" },
  { value: "Scripting", label: "Scripting" },
  { value: "Landing Page", label: "Landing Page" },
  { value: "Help/Consultation", label: "Help/Consultation" },
  { value: "E-Commerce Development", label: "E-Commerce Development" },
  { value: "Full Website Creation", label: "Full Website Creation" },
  { value: "Customization", label: "Customization" },
  { value: "Bug Fixes", label: "Bug Fixes" },
  { value: "Theme/Plugin Installation", label: "Theme/Plugin Installation" },
  { value: "Performance & Security", label: "Performance & Security" },
  { value: "Backup & Migration", label: "Backup & Migration" },
  { value: "Help/Consultation", label: "Help/Consultation" },
  { value: "Mobile Apps", label: "Mobile Apps" },
  { value: "Full App Creation", label: "Full App Creation" },
  { value: "Convert Site to App", label: "Convert Site to App" },
  { value: "App Customization", label: "App Customization" },
  { value: "Bug Fix", label: "Bug Fix" },
  { value: "Help/Consultation", label: "Help/Consultation" },
  { value: "Desktop Applications", label: "Desktop Applications" },
  { value: "Custom Application", label: "Custom Application" },
  { value: "Application Improvements", label: "Application Improvements" },
  { value: "Bug Fixes", label: "Bug Fixes" },
  { value: "Help/Consultation", label: "Help/Consultation" },
  {
    value: "Blockchain & Cryptocurrency",
    label: "Blockchain & Cryptocurrency",
  },
  { value: "Technical Support", label: "Technical Support" },
  {
    value: "Decentralized Applications (dApps)",
    label: "Decentralized Applications (dApps)",
  },
  { value: "Exchange Platforms", label: "Exchange Platforms" },
  { value: "Coins & Tokens", label: "Coins & Tokens" },
  { value: "E-Wallet Development", label: "E-Wallet Development" },
  { value: "NFT Development", label: "NFT Development" },
  { value: "Smart Contracts", label: "Smart Contracts" },
  { value: "NFT Generators", label: "NFT Generators" },
  { value: "NFT Marketplace", label: "NFT Marketplace" },
  { value: "NFT Websites", label: "NFT Websites" },
  { value: "Electronics Engineering", label: "Electronics Engineering" },
  { value: "Embedded Systems & IoT", label: "Embedded Systems & IoT" },
  {
    value: "Printed Circuit Boards (PCB)",
    label: "Printed Circuit Boards (PCB)",
  },
  { value: "DevOps & Cloud", label: "DevOps & Cloud" },
  {
    value: "DevOps & Cloud Consultation",
    label: "DevOps & Cloud Consultation",
  },
  { value: "Infra as Code", label: "Infra as Code" },
  { value: "CI/CD", label: "CI/CD" },
  { value: "Cloud Network & Security", label: "Cloud Network & Security" },
  { value: "Cloud Management", label: "Cloud Management" },
  {
    value: "Cybersecurity & Data Protection",
    label: "Cybersecurity & Data Protection",
  },
  { value: "Consultation", label: "Consultation" },
  { value: "Compliance Services", label: "Compliance Services" },
  {
    value: "Assessment & Penetration Test",
    label: "Assessment & Penetration Test",
  },
  { value: "Cybersecurity Management", label: "Cybersecurity Management" },
  { value: "Support & IT", label: "Support & IT" },
  { value: "Online Coding Lessons", label: "Online Coding Lessons" },
  { value: "Chatbots", label: "Chatbots" },
  { value: "Convert Files", label: "Convert Files" },
  { value: "Convert to a Fillable Form", label: "Convert to a Fillable Form" },
  { value: "Convert to an eBook", label: "Convert to an eBook" },
  {
    value: "Convert to an Editable File",
    label: "Convert to an Editable File",
  },
  { value: "Convert to Another File", label: "Convert to Another File" },
  { value: "User Testing", label: "User Testing" },
  { value: "QA & Review", label: "QA & Review" },
  { value: "Design Review", label: "Design Review" },
  { value: "Code Review", label: "Code Review" },
  { value: "Software Testing", label: "Software Testing" },
  { value: "Other", label: "Other" },
  { value: "Website Development O2O", label: "Website Development O2O" },
  { value: "Event Website", label: "Event Website" },
  { value: "Portfolio Website", label: "Portfolio Website" },
  { value: "Blog", label: "Blog" },
  { value: "Online Store", label: "Online Store" },
  { value: "Business Website", label: "Business Website" },
  { value: "Data", label: "Data" },
  { value: "Databases", label: "Databases" },
  { value: "Consultation", label: "Consultation" },
  {
    value: "Database Administration (DBA)",
    label: "Database Administration (DBA)",
  },
  { value: "Cloud Based Solutions", label: "Cloud Based Solutions" },
  { value: "Queries", label: "Queries" },
  { value: "Design & Optimization", label: "Design & Optimization" },
  { value: "Data Processing", label: "Data Processing" },
  { value: "Consultation", label: "Consultation" },
  { value: "Automations", label: "Automations" },
  { value: "Formulas & Macros", label: "Formulas & Macros" },
  { value: "Data Mining & Scraping", label: "Data Mining & Scraping" },
  { value: "Data Engineering", label: "Data Engineering" },
  { value: "Data Analytics", label: "Data Analytics" },
  { value: "Consultation", label: "Consultation" },
  { value: "Planning & Supply Chain", label: "Planning & Supply Chain" },
  { value: "Business & Financial", label: "Business & Financial" },
  { value: "Surveys & Research", label: "Surveys & Research" },
  { value: "Product & UX", label: "Product & UX" },
  { value: "Marketing & Sales", label: "Marketing & Sales" },
  { value: "Data Visualization", label: "Data Visualization" },
  { value: "Consultation", label: "Consultation" },
  { value: "Reports", label: "Reports" },
  {
    value: "Geographic Information Systems (GIS)",
    label: "Geographic Information Systems (GIS)",
  },
  { value: "Dashboards", label: "Dashboards" },
  { value: "Graphs & Charts", label: "Graphs & Charts" },
  { value: "Data Science", label: "Data Science" },
  { value: "Tagging & Annotation", label: "Tagging & Annotation" },
  { value: "Model Optimization", label: "Model Optimization" },
  { value: "Model Creation", label: "Model Creation" },
  { value: "Full Project", label: "Full Project" },
  { value: "Data Science Consultation", label: "Data Science Consultation" },
  { value: "Data Entry", label: "Data Entry" },
  { value: "Web Research", label: "Web Research" },
  { value: "Copy Paste", label: "Copy Paste" },
  { value: "Data Formatting & Cleaning", label: "Data Formatting & Cleaning" },
  { value: "Other", label: "Other" },
  { value: "Digital Marketing", label: "Digital Marketing" },
  { value: "Social Media Advertising", label: "Social Media Advertising" },
  { value: "Strategy & Planning", label: "Strategy & Planning" },
  { value: "Ads Setup & Management", label: "Ads Setup & Management" },
  { value: "Analytics & Tracking", label: "Analytics & Tracking" },
  { value: "Social Media Marketing", label: "Social Media Marketing" },
  {
    value: "Consultation & Audience Research",
    label: "Consultation & Audience Research",
  },
  {
    value: "Profile Setup & Integration",
    label: "Profile Setup & Integration",
  },
  { value: "Shoppable Content", label: "Shoppable Content" },
  { value: "Social Content", label: "Social Content" },
  { value: "Social Media Management", label: "Social Media Management" },
  { value: "Analytics & Tracking", label: "Analytics & Tracking" },
  { value: "Organic Social Promotions", label: "Organic Social Promotions" },
  { value: "Guest Posting", label: "Guest Posting" },
  {
    value: "Search Engine Optimization (SEO)",
    label: "Search Engine Optimization (SEO)",
  },
  { value: "Keyword Research", label: "Keyword Research" },
  { value: "On-Page SEO", label: "On-Page SEO" },
  { value: "Voice Search SEO", label: "Voice Search SEO" },
  { value: "Technical SEO", label: "Technical SEO" },
  { value: "Off-Page SEO", label: "Off-Page SEO" },
  { value: "Full SEO Package", label: "Full SEO Package" },
  { value: "Competitor Analysis", label: "Competitor Analysis" },
  { value: "Public Relations", label: "Public Relations" },
  { value: "Consultation", label: "Consultation" },
  {
    value: "Events, Conferences & Awards",
    label: "Events, Conferences & Awards",
  },
  { value: "Press Release Pitching", label: "Press Release Pitching" },
  { value: "Strategy & Planning", label: "Strategy & Planning" },
  { value: "Book & eBook Marketing", label: "Book & eBook Marketing" },
  { value: "Podcast Marketing", label: "Podcast Marketing" },
  { value: "Podcast Promotion", label: "Podcast Promotion" },
  {
    value: "Advertising within Podcasts",
    label: "Advertising within Podcasts",
  },
  { value: "Video Marketing", label: "Video Marketing" },
  { value: "YouTube Channel Management", label: "YouTube Channel Management" },
  {
    value: "Consultation & Audience Research",
    label: "Consultation & Audience Research",
  },
  { value: "Video SEO", label: "Video SEO" },
  {
    value: "Video Promotion & Distribution",
    label: "Video Promotion & Distribution",
  },
  { value: "Other", label: "Other" },
  { value: "Email Marketing", label: "Email Marketing" },
  { value: "Campaign Management", label: "Campaign Management" },
  { value: "Email Automations", label: "Email Automations" },
  { value: "Email Platform Support", label: "Email Platform Support" },
  { value: "Audience Development", label: "Audience Development" },
  { value: "Cold Emails", label: "Cold Emails" },
  { value: "Text Message Marketing", label: "Text Message Marketing" },
  { value: "Crowdfunding", label: "Crowdfunding" },
  { value: "Campaign Marketing", label: "Campaign Marketing" },
  { value: "Campaign Creation", label: "Campaign Creation" },
  {
    value: "Search Engine Marketing (SEM)",
    label: "Search Engine Marketing (SEM)",
  },
  {
    value: "Setup & Strategy Consultation",
    label: "Setup & Strategy Consultation",
  },
  {
    value: "Search Engine Marketing Management",
    label: "Search Engine Marketing Management",
  },
  { value: "Shopping Ads", label: "Shopping Ads" },
  { value: "Ad Review & Optimization", label: "Ad Review & Optimization" },
  { value: "Display Advertising", label: "Display Advertising" },
  {
    value: "Campaign Setup & Management",
    label: "Campaign Setup & Management",
  },
  { value: "Ad Review & Optimization", label: "Ad Review & Optimization" },
  { value: "Retargeting", label: "Retargeting" },
  { value: "Native Advertising", label: "Native Advertising" },
  { value: "Audio Advertising", label: "Audio Advertising" },
  { value: "Web Traffic", label: "Web Traffic" },
  { value: "Web Analytics", label: "Web Analytics" },
  { value: "Setup", label: "Setup" },
  { value: "Tracking & Reporting", label: "Tracking & Reporting" },
  { value: "Optimization", label: "Optimization" },
  { value: "Bug Fixes", label: "Bug Fixes" },
  { value: "Marketing Advice", label: "Marketing Advice" },
  { value: "Marketing Mentorship", label: "Marketing Mentorship" },
  { value: "Marketing Lessons", label: "Marketing Lessons" },
  { value: "Influencer Marketing", label: "Influencer Marketing" },
  { value: "Strategy & Research", label: "Strategy & Research" },
  { value: "Shoutouts & Promotion", label: "Shoutouts & Promotion" },
  { value: "Long-Term Collaborations", label: "Long-Term Collaborations" },
  { value: "Marketing Strategy", label: "Marketing Strategy" },
  { value: "Consulting", label: "Consulting" },
  { value: "Buyer Persona", label: "Buyer Persona" },
  { value: "Marketing Plans", label: "Marketing Plans" },
  { value: "Community Management", label: "Community Management" },
  { value: "Planning, Strategy & Setup", label: "Planning, Strategy & Setup" },
  { value: "Sourcing & Recruitment", label: "Sourcing & Recruitment" },
  {
    value: "Growth, Partnerships & Monetization",
    label: "Growth, Partnerships & Monetization",
  },
  { value: "Management & Engagement", label: "Management & Engagement" },
  { value: "Social Listening", label: "Social Listening" },
  { value: "Event Marketing", label: "Event Marketing" },
  { value: "Local SEO", label: "Local SEO" },
  { value: "Google My Business", label: "Google My Business" },
  {
    value: "Local Citations and Directories",
    label: "Local Citations and Directories",
  },
  { value: "E-Commerce Marketing", label: "E-Commerce Marketing" },
  { value: "Promoted Listings", label: "Promoted Listings" },
  { value: "E-Commerce SEO", label: "E-Commerce SEO" },
  { value: "Website Promotion", label: "Website Promotion" },
  { value: "Affiliate Marketing", label: "Affiliate Marketing" },
  { value: "Affiliates Recruitment", label: "Affiliates Recruitment" },
  { value: "Marketing Funnels", label: "Marketing Funnels" },
  { value: "Link Promotion", label: "Link Promotion" },
  { value: "Program Strategy & Setup", label: "Program Strategy & Setup" },
  { value: "Mobile App Marketing", label: "Mobile App Marketing" },
  { value: "App Store Optimization", label: "App Store Optimization" },
  { value: "App Promotion", label: "App Promotion" },
  { value: "Music Promotion", label: "Music Promotion" },
  { value: "Organic Promotion", label: "Organic Promotion" },
  { value: "Paid Advertising", label: "Paid Advertising" },
  { value: "Music Streaming Services", label: "Music Streaming Services" },
  { value: "Playlists and Placements", label: "Playlists and Placements" },
];
