const layers: { [key: string]: string[] } = {
  "Back Accessories": [
    "BACKPACK BLACK KEYBOARD-7.png",
    "BACKPACK BROWN-68.png",
    "BACKPACK CANDIES-83.png",
    "BACKPACK WHITE-58.png",
    "GAMING CHAIR BLACK-11.png",
    "GAMING CHAIR WHITE-19.png",
    "JETPACK-2.png",
    "KATANA BLACK-34.png",
    "KATANA RED WHITE-28.png",
    "NONE-690.png",
  ],
  Background: [
    "ARC-15.png",
    "BEE-11.png",
    "BLACK-108.png",
    "BLUE-107.png",
    "BUBBLE-56.png",
    "BUBBLE RED-41.png",
    "BUBBLE YELLOW-44.png",
    "GOLD-69.png",
    "GREEN-96.png",
    "GREY-94.png",
    "MAGAZINE-29.png",
    "METASTORY-36.png",
    "MONEY-7.png",
    "MOON-6.png",
    "PAINT-28.png",
    "PINK-85.png",
    "PURPLE-80.png",
    "RED CLOUDS-68.png",
    "SNOW-20.png",
  ],
  Clothes: [
    "ASTRONAUT WHITE-2.png",
    "BIG PUFFER CAMO-56.png",
    "BIG PUFFER LOGO BLUE-65.png",
    "BIG PUFFER LOGO PURPLE-70.png",
    "BIG PUFFER LOGO WHITE-58.png",
    "BIG PUFFER WHITE-60.png",
    "BOMBER BLACK-17.png",
    "BOMBER BLUE-17.png",
    "BOMBER GREY-17.png",
    "BOMBER GREY RED-19.png",
    "CARDIGAN BILLIONYMOUS-16.png",
    "CARDIGAN BLUE-16.png",
    "CARDIGAN BROWN-26.png",
    "CARDIGAN GREY-29.png",
    "DENIM JACKET BLUE RED-14.png",
    "DENIM JACKET YELLOW-14.png",
    "HOODIE BLACK YELLOW-75.png",
    "HOODIE FAN ART-54.png",
    "HOODIE HEART-81.png",
    "HOODIE SPIDER-12.png",
    "HOODIE TAINTED BLUE-37.png",
    "JACKET BLACK-15.png",
    "JACKET PINK-15.png",
    "JAIL BLACK RED-8.png",
    "JAIL BLUE-7.png",
    "JAIL ORANGE-8.png",
    "JERSEY GREEN-22.png",
    "JERSEY RED-24.png",
    "JERSEY YELLOW-20.png",
    "PUFFER CHECKBOARD-10.png",
    "PUFFER GREEN-10.png",
    "PUFFER RED-9.png",
    "PULLOVER-35.png",
    "SPORT TRACKSUIT-10.png",
    "SPORT TRACKSUIT BLUE-10.png",
    "SUIT BLACK RED-6.png",
    "SUIT BLACK YELLOW-4.png",
    "SUIT BLUE-3.png",
    "SUIT GREY-5.png",
    "TRACKSUIT CAMO BLUE-11.png",
    "TRACKSUIT CAMO ORANGE-13.png",
  ],
  "Ears Wear": [
    "MB LOGO SILVER-442.png",
    "NONE-8529.png",
    "RING GOLD-292.png",
    "RING SILVER-264.png",
    "SWORD GOLD-246.png",
    "SWORD SILVER-226.png",
  ],
  Eyes: [
    "BLUE-154.png",
    "CIRCLE-140.png",
    "FLAME-123.png",
    "GREEN-26.png",
    "HEART-108.png",
    "HYPNOTIZED-72.png",
    "LAVA-15.png",
    "MULTICOLOR-61.png",
    "NORMAL-177.png",
    "PURPLE-48.png",
    "RED-41.png",
    "WATER-35.png",
  ],
  "Face Accessories": [
    "3D GLASSES BLUE GUM-11.png",
    "3D GLASSES CIGAR-22.png",
    "3D GLASSES LOLLIPOP-46.png",
    "3D GLASSES RED SODA-50.png",
    "BEARD BLACK-11.png",
    "BLACK MUSTACHE BLACK SUNGLASSES-7.png",
    "BLUE GUM-53.png",
    "BLUE SODA-17.png",
    "CIGAR-37.png",
    "CIRCLE GLASSES PENCIL-11.png",
    "CIRCLE GLASSES RED SODA-10.png",
    "COVID MASK-34.png",
    "ETH COIN-36.png",
    "FACE MASK BLACK-10.png",
    "FACE MASK BLACK WHITE-9.png",
    "FACE MASK BLACK WHITE CIGAR-9.png",
    "FACE MASK PENCIL-9.png",
    "FUTURE GLASSES-8.png",
    "FUTURE GLASSES GUM RED-33.png",
    "FUTURE GLASSES LOLLIPOP-9.png",
    "FUTURES GLASSES MOUSE-5.png",
    "HEART GLASSES-8.png",
    "HEART GLASSES PIPER-8.png",
    "LOLLIPOP-30.png",
    "METAVERSE MASK-8.png",
    "METAVERSE MASK BLUE SODA-8.png",
    "MUSTACHE-7.png",
    "NONE-52.png",
    "PACIFIER BLACK WHITE-22.png",
    "PACIFIER GREY-21.png",
    "PENCIL-7.png",
    "PIPER-7.png",
    "PIXEL GLASSES-7.png",
    "PIXEL GLASSES BLUE SODA-20.png",
    "PM GLASSES COVID MASK-29.png",
    "PM GLASSES ETH COIN-18.png",
    "PM WHITE GLASSES PACIFIER-32.png",
    "RED GUM-23.png",
    "RED SODA-28.png",
    "SQUARE GLASSES BLACK WHITE-16.png",
    "SQUARE GLASSES BLACK WHITE BEARD-27.png",
    "SQUARE GLASSES GOLD-3.png",
    "SQUARE GLASSES INFRARED-3.png",
    "SQUARE GLASSES INFRARED RED SODA-19.png",
    "SQUARE GLASSES RED PACIFIER BLACK WHITE-15.png",
    "SQUARE GLASSES TRANSPARENT BLACK BEARD-26.png",
    "SUNGLASSES BLACK-12.png",
    "SUNGLASSES BLACK CIGAR-14.png",
    "SUNGLASSES TRANSPARENT-12.png",
    "SUNGLASSES UP WHITE-25.png",
    "SUNGLASSES UP WHITE PACIFIER-24.png",
    "VR BLACK-2.png",
    "VR BLACK BEARD BLACK-2.png",
    "VR WHITE-1.png",
    "VR WHITE GUM RED-1.png",
  ],
  Hair: [
    "AFRO BLOND-15.png",
    "AFRO BROWN-13.png",
    "AFRO GREY-18.png",
    "AFRO WHITE RED BLACK-14.png",
    "BACKWARD BLACK-63.png",
    "BACKWARD MASK-3.png",
    "BLACKWARD BROWN-61.png",
    "BOWL BLOND-20.png",
    "BOWL BLUE-21.png",
    "BOWL BROWN-19.png",
    "BOWL MASK-2.png",
    "BRAID BLACK WHITE-24.png",
    "BRAID BLACK YELLOW-22.png",
    "BRAID MASK-2.png",
    "BRAID WHITE-25.png",
    "BUCKET HAT BLACK-12.png",
    "BUCKET HAT CURLY-11.png",
    "CAP MULTICOLOR-19.png",
    "CAP YELLOW RED BLACK-19.png",
    "COWBOY HAT BLACK-5.png",
    "COWBOY HAT WHITE-5.png",
    "CURLY BLOND-39.png",
    "CURLY BROWN-41.png",
    "CURLY WHITE-42.png",
    "CURLY WHITE RED BLACK-3.png",
    "LOCKS BLACK-59.png",
    "LOCKS WHITE-58.png",
    "NONE-7.png",
    "SHORT BLACK-33.png",
    "SHORT BLUE-32.png",
    "SHORT HEART BLACK-4.png",
    "SHORT HEARTH PINK-1.png",
    "SHORT WHITE-37.png",
    "SIDED BLACK-10.png",
    "SIDED WHITE-8.png",
    "TWIST BLACK-29.png",
    "TWIST BLUE-26.png",
    "TWIST REDWHITE-25.png",
    "WAVE BLOND-51.png",
    "WAVE BLUE-44.png",
    "WAVE BROWN-57.png",
    "WAVE MASK-1.png",
  ],
  Rare: ["AUREOLE-10.png", "NONE-990.png"],
  Skin: [
    "BLACK-235.png",
    "BLACK TATOO-12.png",
    "MIXED-237.png",
    "MIXED TATOO-13.png",
    "SILVER-11.png",
    "WHITE-478.png",
    "WHITE TATOO-14.png",
  ],
};

export default layers;
